### ISSUE TITLE
[User-Story] Als Suchender möchte ich nach Angeboten suchen, um die für mich passende Fahrt zu finden.

### ISSUE THREAD

**Issue by wrth1337** [wrth1337/MyCargonaut#11]
# Overview
Als Suchender möchte ich nach Angeboten suchen, um die für mich passende Fahrt zu finden.

# Subtasks
- [x] #72
- [x] #73
- [x] #74
- [x] #106
- [x] #75

☑️ Definition of Done checklist

Frontend

- [x] Are all functions implemented?
- [ ] Are there front-end tests that test the appearance of the mockup?
- [x] Do the associated components look like the mockup?

Backend

- [x] Are all necessary routes documented via swagger?
- [x] Are all necessary methods tested via Jest (positive and negative tests)?

Is the user story finished to such an extent that no further work is required after the pull request (excluding hotfixes and adjustments)?

**Comment by wrth1337** [comment]
Wurde in Dev gemerged.
