### ISSUE TITLE
[User-Story] Als Nutzer möchte ich den Status eines Bookings einsehen können, um mir ein Bild darüber zu schaffen, wie weit die Buchung fortgeschritten ist.

### ISSUE THREAD

**Issue by wrth1337** [wrth1337/MyCargonaut#111]
# Overview
Als Nutzer möchte ich den Status eines Bookings einsehen können, um mir ein Bild darüber zu schaffen, wie weit die Buchung fortgeschritten ist.

# Subtasks
- [x] create a backend route to get the status of the ad
- [x] test the backend route
- [x] write swagger documentation for backend route
- [x] create the frontend
- [x] test frontend

**Comment by wrth1337** [comment]
Wurde in anderem Issue fertig gestellt.
