### ISSUE TITLE
[User-Story] Als Mitfahrer möchte ich nach beendigter Fahrt den Fahrer bewerten können.

### ISSUE THREAD

**Issue by hannafeddersen** [wrth1337/MyCargonaut#136]
# Overview
As a passenger, I would like to be able to rate the driver after the journey has been completed.
# Subtasks
- [ ] create a backend route to post rating in database
- [ ] test the backend route
- [ ] write swagger documentation for backend route
- [ ] create the frontend
- [ ] test frontend

**Comment by JonathanRech** [comment]
Löst außerdem Issue #109

**Comment by wrth1337** [comment]
Wurde weiter bearbeitet durch @JonathanRech und @wrth1337
