### ISSUE TITLE
[User-Story] Als Suchender möchte ich nach Kriterien suchen können, um nur passende Angebote angezeigt zu bekommen.

### ISSUE THREAD

**Issue by wrth1337** [wrth1337/MyCargonaut#14]
# Overview
Als Suchender möchte ich nach Kriterien suchen können, um nur passende Angebote angezeigt zu bekommen.
In diesem Task soll die Anzeige der Suchergebnisse angezeigt werden.

# Subtasks
- [x] Add backend routes in ad.js
- [x] Document routes via Swagger
- [x] Add ResultPage Component Frontend
- [x] Add Add-Card Component Frontend
- [x] Add Frontend functionalities
