### ISSUE TITLE
[User-Story] Als BenutzerIn möchte ich Kommentare zu einem Ad hinzufügen können, um Fragen oder sonstiges zu klären

### ISSUE THREAD

**Issue by wrth1337** [wrth1337/MyCargonaut#184]
# Overview
[User-Story] Als BenutzerIn möchte ich Kommentare zu einem Ad hinzufügen können, um Fragen oder sonstiges zu klären

# Subtasks
- [x] Backend-Tests erstellen
- [x] Backend-Routen erstellen auf Basis der Tests
- [ ] Herstellung der Chat-Funktionalität im Frontend
- [ ] UI/UX (Besoners Hervorhebung von Ad-Erstellern und buchenden Personen)
