### ISSUE TITLE
Als Benutzer möchte ich dass meine Daten verschlüsselt übertragen werden

### ISSUE THREAD

**Issue by marcel951** [wrth1337/MyCargonaut#194]
# Overview

# Subtasks
- [ ] Erstellen eines Scriptes um die benötigten Zertifikate mit openssl zu generieren und im korrekten Verzeichnis abzulegen
- [ ] Integration der generierten Zertifikate in den Docker Build Prozess um diese in der lokalen Umgebung nutzen zu können
- [ ] Testen der Konfiguration
