### ISSUE TITLE
[User-Story] Als Nutzer möchte ich einen neuen Account anlegen können.

### ISSUE THREAD

**Issue by JonathanRech** [wrth1337/MyCargonaut#36]
# Overview
Als Nutzer möchte ich neuen Account anlegen können.
# Subtasks
- [x] Backend-Funktionalität herstellen
- [x] Backend-Tests schreiben
- [x] Frontend-Funktionalität herstellen
- [x] Frontend-Tests schreiben
- [x] Datenbankanbindung
